server:
  host: 'odoo-esmith-0627-stage-8904751.dev.odoo.com'
  db_name: 'odoo-esmith-0627-stage-8904751'
  url: 'https://odoo-esmith-0627-stage-8904751.dev.odoo.com/api/v1/boq_import_api/swagger.json?token=97385109-c122-4300-bbee-39cd7ba687c2&db=odoo-esmith-0627-stage-8904751'
  # token_file: 'c:\odoo\config\token.yaml'
  # StripMtext_file: 'O:\\autolisp\\StripMtext v5-0b.lsp'
  # read_csv_file: 'O:\\autolisp\\read_csv.lsp'
  # contract_product_file: 'O:\\autolisp\\contract_product.lsp'
  token_file: 'c:\odoo\config\token.yaml'
  StripMtext_file: 'C:\\odoo\\odoo_autocad\\autolisp\\StripMtext v5-0b.lsp'
  read_csv_file: 'C:\\odoo\\odoo_autocad\\autolisp\\read_csv.lsp'
  contract_product_file: 'C:\\odoo\\odoo_autocad\\autolisp\\contract_product.lsp'
