server:
  host: 'odoo-esmith-0216-stage-7291003.dev.odoo.com'
  db_name: 'odoo-esmith-0216-stage-7291003'
  url: 'https://odoo-esmith-0216-stage-7291003.dev.odoo.com/api/v1/boq_import_api/swagger.json?token=1a7119c2-1feb-401e-bf8d-c1fe5634582d&db=odoo-esmith-0216-stage-7291003'
  token_file: 'c:\odoo\config\token.yaml'
  StripMtext_file: 'C:\\odoo\\odoo_autocad\\autolisp\\StripMtext v5-0b.lsp'
  read_csv_file: 'C:\\odoo\\odoo_autocad\\autolisp\\read_csv.lsp'
  contract_product_file: 'C:\\odoo\\odoo_autocad\\autolisp\\contract_product.lsp'
