server:
  host: 'e-smith.odoo.com'
  db_name: 'odoo13-esmith-master-1011507'
  url: 'https://e-smith.odoo.com/api/v1/boq_import_api/swagger.json?token=1a7119c2-1feb-401e-bf8d-c1fe5634582d&db=odoo13-esmith-master-1011507'
  token_file: 'c:\odoo\config\token.yaml'
  StripMtext_file: 'O:\\autolisp\\StripMtext v5-0b.lsp'
  read_csv_file: 'O:\\autolisp\\read_csv.lsp'
  contract_product_file: 'O:\\autolisp\\contract_product.lsp'
